/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContentStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'pdfSource' : IDL.Vec(IDL.Nat8),
  'courseId' : IDL.Text,
});
export const TraineeProgress = IDL.Record({
  'completedLessons' : IDL.Vec(IDL.Text),
  'enrolledCourses' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'enrollInCourse' : IDL.Func([IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
  'getLesson' : IDL.Func([IDL.Text], [Lesson], ['query']),
  'getLessonsByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getTraineeProgress' : IDL.Func([], [TraineeProgress], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importPdf' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markLessonCompleted' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCourse' : IDL.Func([Course], [], []),
  'saveLesson' : IDL.Func([Lesson], [], []),
  'setContentStatus' : IDL.Func([IDL.Text, ContentStatus, IDL.Bool], [], []),
  'updateCourse' : IDL.Func([Course], [], []),
  'updateLesson' : IDL.Func([Lesson], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContentStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'pdfSource' : IDL.Vec(IDL.Nat8),
    'courseId' : IDL.Text,
  });
  const TraineeProgress = IDL.Record({
    'completedLessons' : IDL.Vec(IDL.Text),
    'enrolledCourses' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'enrollInCourse' : IDL.Func([IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
    'getLesson' : IDL.Func([IDL.Text], [Lesson], ['query']),
    'getLessonsByCourse' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getTraineeProgress' : IDL.Func([], [TraineeProgress], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importPdf' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markLessonCompleted' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCourse' : IDL.Func([Course], [], []),
    'saveLesson' : IDL.Func([Lesson], [], []),
    'setContentStatus' : IDL.Func([IDL.Text, ContentStatus, IDL.Bool], [], []),
    'updateCourse' : IDL.Func([Course], [], []),
    'updateLesson' : IDL.Func([Lesson], [], []),
  });
};

export const init = ({ IDL }) => { return []; };